policy_list = [
    'Wikipedia:IP封禁例外',
    'Wikipedia:不要人身攻击',
    'Wikipedia:不要伤害新手',
    'Wikipedia:不要包含原始资料的副本',
    'Wikipedia:不要為闡釋觀點而擾亂維基百科',
    'Wikipedia:不要訴諸法律威脅',
    'Wikipedia:中立的观点',
    'Wikipedia:五大支柱',
    'Wikipedia:人事任免投票資格',
    'Wikipedia:什么是条目',
    'Wikipedia:介面管理員',
    'Wikipedia:使用条款',
    'Wikipedia:侵犯著作权',
    'Wikipedia:保護方針',
    'Wikipedia:修訂版本刪除',
    'Wikipedia:假定善意',
    'Wikipedia:傀儡',
    'Wikipedia:儿童保护',
    'Wikipedia:共识',
    'Wikipedia:关注度',
    'Wikipedia:关注度 (人物)',
    'Wikipedia:关注度 (地理特征)',
    'Wikipedia:关注度 (数字)',
    'Wikipedia:关注度 (组织)',
    'Wikipedia:关注度 (虚构)',
    'Wikipedia:分类名称',
    'Wikipedia:列明来源',
    'Wikipedia:删除方针',
    'Wikipedia:利益衝突',
    'Wikipedia:剧透内容',
    'Wikipedia:勇于更新页面',
    'Wikipedia:勇於提問',
    'Wikipedia:可供查證',
    'Wikipedia:可靠來源 (醫學)',
    'Wikipedia:可靠来源',
    'Wikipedia:可靠来源/布告板/评级指引',
    'Wikipedia:命名常規 (日本動漫遊戲條目)',
    'Wikipedia:命名常规',
    'Wikipedia:命名常规 (人名)',
    'Wikipedia:命名常规 (化学)',
    'Wikipedia:命名常规 (国际关系)',
    'Wikipedia:命名常规 (技术限制)',
    'Wikipedia:命名常规 (电子游戏)',
    'Wikipedia:命名常规 (音乐)',
    'Wikipedia:回退功能',
    'Wikipedia:地区词处理',
    'Wikipedia:基金會行動',
    'Wikipedia:外部链接',
    'Wikipedia:大量帳號建立者',
    'Wikipedia:大量訊息發送者',
    'Wikipedia:字詞轉換處理',
    'Wikipedia:存廢覆核方針',
    'Wikipedia:封禁方针',
    'Wikipedia:小小作品',
    'Wikipedia:建设性意见',
    'Wikipedia:志愿者回复团队',
    'Wikipedia:快速保留',
    'Wikipedia:快速删除方针',
    'Wikipedia:忽略所有规则',
    'Wikipedia:拉票',
    'Wikipedia:捷徑',
    'Wikipedia:文件使用方针',
    'Wikipedia:文明',
    'Wikipedia:新聞動態',
    'Wikipedia:新聞動態/重複發生的項目',
    'Wikipedia:新頁面巡查',
    'Wikipedia:方針與指引',
    'Wikipedia:有償編輯方針',
    'Wikipedia:机器用户',
    'Wikipedia:条目所有权',
    'Wikipedia:格式手冊/不要華而不實',
    'Wikipedia:格式手冊/作品列表',
    'Wikipedia:格式手冊/序言章節',
    'Wikipedia:格式手冊/文字格式',
    'Wikipedia:格式手冊/版面佈局',
    'Wikipedia:格式手冊/電視',
    'Wikipedia:格式手册',
    'Wikipedia:格式手册/两岸四地用语',
    'Wikipedia:格式手册/列表',
    'Wikipedia:格式手册/嵌入列表',
    'Wikipedia:格式手册/旗帜',
    'Wikipedia:格式手册/日期和数字',
    'Wikipedia:格式手册/朝鲜半岛用语',
    'Wikipedia:格式手册/标点符号',
    'Wikipedia:格式手册/缩写',
    'Wikipedia:格式手册/虚构',
    'Wikipedia:格式手册/链接',
    'Wikipedia:標誌',
    'Wikipedia:模板樣式',
    'Wikipedia:模板編輯員',
    'Wikipedia:機械人方針',
    'Wikipedia:檔案名稱',
    'Wikipedia:檔案移動員',
    'Wikipedia:權限申請',
    'Wikipedia:消歧义',
    'Wikipedia:游戏维基规则',
    'Wikipedia:爭議解決指引',
    'Wikipedia:生者傳記',
    'Wikipedia:用戶查核方針',
    'Wikipedia:用戶頁',
    'Wikipedia:用户名',
    'Wikipedia:申请成为管理人员',
    'Wikipedia:电子游戏条目指引',
    'Wikipedia:监督',
    'Wikipedia:破坏',
    'Wikipedia:礼仪',
    'Wikipedia:禁制方针',
    'Wikipedia:签名',
    'Wikipedia:管理员',
    'Wikipedia:管理員的離任',
    'Wikipedia:管理戰',
    'Wikipedia:編輯戰',
    'Wikipedia:繁简处理',
    'Wikipedia:维基百科不是什么',
    'Wikipedia:维基百科不是词典',
    'Wikipedia:编辑方针',
    'Wikipedia:翻譯指引',
    'Wikipedia:自傳',
    'Wikipedia:草稿命名空间',
    'Wikipedia:著作权信息',
    'Wikipedia:行政员',
    'Wikipedia:解除權限方針',
    'Wikipedia:討論頁指引',
    'Wikipedia:誹謗',
    'Wikipedia:账号请求',
    'Wikipedia:账户安全',
    'Wikipedia:跨維基匯入者',
    'Wikipedia:过度分类',
    'Wikipedia:通用行為準則',
    'Wikipedia:道路特殊收錄限制列表',
    'Wikipedia:避免地域中心',
    'Wikipedia:重定向',
    'Wikipedia:钱币学条目指引',
    'Wikipedia:關注度 (交通)',
    'Wikipedia:關注度 (天體)',
    'Wikipedia:關注度 (學者)',
    'Wikipedia:關注度 (幾何圖形)',
    'Wikipedia:關注度 (性質表)',
    'Wikipedia:關注度 (書籍)',
    'Wikipedia:關注度 (氣旋)',
    'Wikipedia:關注度 (運動員)',
    'Wikipedia:關注度 (電視劇)',
    'Wikipedia:關注度 (音樂)',
    'Wikipedia:關閉存廢討論指引',
    'Wikipedia:隐退',
    'Wikipedia:非原创研究',
    'Wikipedia:非條目頁面命名',
    'Wikipedia:非歧视方针',
    'Wikipedia:非自由内容使用准则',
    'Wikipedia:非自由版权图片大小',
    'Wikipedia:頁面分類',
    'Wikipedia:騷擾',
    'Wikipedia:高風險模板',
]
